[tool.poetry]
name = "las-trx"
version = "0.2.2"
description = "Convert lidar .las/.laz file coordinates between various ITRF realizations and NAD83 CSRS."
authors = ["Taylor Denouden <taylordenouden@gmail.com>"]
repository = "https://github.com/HakaiInstitute/LAS-TRX"

[tool.poetry.dependencies]
python = "^3.9,<3.11"
csrspy = "^0.2.3"
laszip = "^0.1.0"
pydantic = "^1.9.0"
PySide2 = "^5.15.2"
pyproj = "^3.3.0"
laspy = "^2.1.2"

[tool.poetry.dev-dependencies]
pyinstaller = "^4.10"
pytest = "^7.1.1"
black = "^22.3.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
